<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.2.0" />
        <PackageReference Include="MediatR" Version="12.4.1" />
        <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="9.0.0" />
    </ItemGroup>


    <ItemGroup>
        <Folder Include="EmailMessages\Commands\Dto\" />
        <Folder Include="Machines\Commands\Dto\" />
        <Folder Include="Machines\Queries\Dto\" />
        <Folder Include="RecordTypes\Queries\Dto\" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\MaintenanceChronicle.Data\MaintenanceChronicle.Data.csproj" />
    </ItemGroup>
</Project>
