<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="MailKit" Version="4.18.1" />
    <PackageReference Include="MimeKit" Version="4.18.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Customers\Commands\" />
    <Folder Include="EmailMessages\Queries\" />
    <Folder Include="MaintenanceReminders\Queries\" />
    <Folder Include="RecordTypes\Queries\" />
    <Folder Include="Tenants\Queries\" />
    <Folder Include="UserTenant\Commands\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaintenanceChronicle.Application.Contracts\MaintenanceChronicle.Application.Contracts.csproj" />
      <ProjectReference Include="..\MaintenanceChronicle.Data\MaintenanceChronicle.Data.csproj" />
      <ProjectReference Include="..\MaintenanceChronicle.Infrastructure\MaintenanceChronicle.Infrastructure.csproj" />
  </ItemGroup>

</Project>
